general.import = [
  "/home/nandax/.local/share/nvim/lazy/melange-nvim/term/alacritty/melange_dark.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.footer_bar]
foreground = "#ECE1D7"
background = "#292522"

[colors.line_indicator]
foreground = "#ECE1D7"
background = "#292522"

[colors.search.focused_match]
foreground = "#292522"
background = "#D47766"

[colors.search.matches]
foreground = "#D47766"
background = "#292522"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"


[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
{ key = "J", mods = "Control", action = "ToggleViMode"},
]

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
